name: Feature request
description: Suggest a feature
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the feature has not already been requested in the issue tracker.

        Thanks for helping us improve Win Stays!
  - type: dropdown
    attributes:
      label: Component
      description: What stakeholder is the feature for?
      multiple: true
      options:
        - Travellers
        - Accommodation Providers
        - Event Organizers
        - Other (please describe)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the feature you would like
      description: Please also describe what the feature is aiming to solve, if relevant.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context to the feature (like screenshots, resources)
